# This file lists translatable strings used in the Android app which don't appear anywhere else
# in the Electron Cash repository. Some of them only differ in capitalization or punctuation:
# see https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98
#
# Please keep the strings in alphabetical order.

# This file is never actually imported, but keep syntax checkers happy.
from gettext import gettext as _, ngettext

ngettext("%d address", "%d addresses", 1)
_("(%1$d of %2$d)")
_("Are you sure you want to delete your wallet \'%s\'?")
_("BIP39 seed")
_("Block explorer")
_("%s bytes")
_("Cannot process a URI while this dialog is open.")
_("Cannot specify private keys and addresses in the same wallet.")
_("Change password")
_("Close wallet")
_("Confirm password")
_("%1$d tx (%2$d unverified)")
_("Console")
_("Consolidate")
_("Copyright © 2017-2024 Electron Cash LLC and the Electron Cash developers.")
_("Cosigner %d")
_("Current password")
_("Delete wallet")
_("Derivation invalid")
_("Disable")
_("Disconnect")
_("Do you want to close this wallet?")
_("Enable")
_("Enable/Disable Fusion")
_("Enter password")
_("Export wallet")
_("Fan Out")
_("Filename is too long")
_("Filenames cannot contain the '/' character")
_("For support, please visit us on <a href='https://github.com/Electron-Cash/Electron-Cash/issues'>"
  "GitHub</a> or on <a href='https://t.me/electroncashwallet'>Telegram</a>.")
_("Fuse Forever")
_("Fusion")
_("Fusion Depth")
_("Fusion Server Port")
_("Fusion Server URL")
_("Fusion Server URL")
_("Fusion Settings")
_("Fusion Type")
_("Fusion Use SSL")
_("ID")
_("Import addresses or private keys")
_("Invalid address")
_("List of fusions")
_("Load transaction")
_("Made with <a href='https://chaquo.com/chaquopy'>Chaquopy</a>, the Python SDK for Android.")
_("Master public key")
_("Master public keys")
_("New password")
_("New wallet")
_("No wallet")
_("No wallet is open.")
_("Normal")
_("Not a valid address or private key: '%s'")
_("Passphrase")
_("Paste or scan a transaction in hex format:")
_("Press the menu button above to open or create one.")
_("Rename wallet")
_("Request")
_("Restore from seed")
_("Save")
_("Scan QR")
_("Show seed")
_("Sign transaction")
_("Signed transaction")
_("Size")
_("Spend only fused coins")
_("System")
ngettext("Sweep %d input", "Sweep %d inputs", 1)
_("Tor not found. You need to have a Tor instance running on your device.")
_("Transaction not found")
_("Use a master key")
_("Wallet exported successfully")
_("Wallet information")
_("Wallet renamed successfully")
_("Wallet seed")
_("You don't have any contacts.")
_("fusion")
